# Generated by Django 5.0.4 on 2025-11-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_telegram_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255, null=True)),
                ('source', models.CharField(choices=[('canteen', 'Столовая'), ('qr_patrol', 'QR-обход'), ('dispatch', 'Диспетчеризация'), ('system', 'Системное')], default='system', max_length=50, verbose_name='Источник')),
                ('text', models.TextField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
