# Generated by Django 5.0.4 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0019_dutyaction"),
        ("users", "0008_notification_is_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="duty_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="dispatch.dutyaction",
                verbose_name="Действие с дежурством",
            ),
        ),
    ]
