# Generated by Django 5.0.4 on 2026-01-07 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification_duty_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +7XXXXXXXXXX', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('expires_at', models.DateTimeField(verbose_name='Время истечения')),
                ('is_used', models.BooleanField(default=False, verbose_name='Использован ли')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен восстановления пароля',
                'verbose_name_plural': 'Токены восстановления пароля',
                'ordering': ['-created_at'],
            },
        ),
    ]
