# Generated by Django 5.0.4 on 2025-11-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_alter_dutypoint_level_0_role_and_more'),
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='notification_duty_is_coming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_is_coming', to='users.notification'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='notification_need_to_open',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='need_to_open', to='users.notification'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
