# Generated by Django 5.0.4 on 2025-01-XX XX:XX

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0018_alter_duty_notification_duty_is_coming_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DutyAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("refusal", "Отказ от дежурства"),
                            ("transfer", "Передача дежурства"),
                            ("acceptance", "Принятие дежурства"),
                        ],
                        max_length=20,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Причина"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(default=False, verbose_name="Решено ли"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время решения"
                    ),
                ),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="dispatch.duty",
                        verbose_name="Дежурство",
                    ),
                ),
                (
                    "new_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_duty_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Новый дежурный",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_duty_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Решено пользователем",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие с дежурством",
                "verbose_name_plural": "Действия с дежурствами",
                "ordering": ["-created_at"],
            },
        ),
    ]
