# Generated by Django 5.0.4 on 2026-01-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0019_dutyaction'),
        ('users', '0010_user_phone_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='notification_duty_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_reminder', to='users.notification'),
        ),
    ]
