# Generated by Django 5.0.4 on 2026-01-24 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0020_duty_notification_duty_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekendDutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(5, 'Суббота'), (6, 'Воскресенье')], help_text='Только суббота/воскресенье', verbose_name='День недели')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_assignments', to='dispatch.dutyrole', verbose_name='Роль дежурства')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Дежурный')),
            ],
            options={
                'verbose_name': 'Дежурный на выходные',
                'verbose_name_plural': 'Дежурные на выходные',
            },
        ),
        migrations.AddConstraint(
            model_name='weekenddutyassignment',
            constraint=models.UniqueConstraint(fields=('role', 'weekday'), name='unique_weekend_assignment'),
        ),
    ]
