# Generated by Django 5.0.4 on 2026-02-09 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0021_weekenddutyassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weekenddutyassignment',
            name='unique_weekend_assignment',
        ),
        migrations.RemoveField(
            model_name='weekenddutyassignment',
            name='weekday',
        ),
        migrations.AddConstraint(
            model_name='weekenddutyassignment',
            constraint=models.UniqueConstraint(fields=('role',), name='unique_weekend_assignment'),
        ),
    ]
