# Generated by Django 5.0.4

from django.db import migrations, models


def keep_one_assignment_per_role(apps, schema_editor):
    """Оставляем одну запись на роль (с минимальным id), остальные удаляем."""
    from django.db.models import Min

    WeekendDutyAssignment = apps.get_model("dispatch", "WeekendDutyAssignment")
    kept_ids = set(
        WeekendDutyAssignment.objects.values("role_id").annotate(
            min_id=Min("id")
        ).values_list("min_id", flat=True)
    )
    WeekendDutyAssignment.objects.exclude(id__in=kept_ids).delete()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0021_weekenddutyassignment_and_more"),
    ]

    operations = [
        migrations.RunPython(keep_one_assignment_per_role, noop),
        migrations.RemoveConstraint(
            model_name="weekenddutyassignment",
            name="unique_weekend_assignment",
        ),
        migrations.RemoveField(
            model_name="weekenddutyassignment",
            name="weekday",
        ),
        migrations.AddConstraint(
            model_name="weekenddutyassignment",
            constraint=models.UniqueConstraint(
                fields=("role",), name="unique_weekend_assignment"
            ),
        ),
    ]
